name: Build and Push Docker Image

on:
  push:
    branches:
      - main # You can change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build nginx image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: "{{defaultContext}}:docker-build"
        tags: "${{ secrets.DOCKER_USERNAME }}/nginx-app:v4"
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false

    - name: Update APP_VERSION
      run: sed -i 's/APP_VERSION=.*/APP_VERSION=v4/' userdata.tpl
